"""add is_interactive flag to documents

Revision ID: 0383874c3306
Revises: 9f22e0351020
Create Date: 2025-10-10 18:45:15.310579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0383874c3306'
down_revision: Union[str, None] = '9f22e0351020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_interactive', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_interactive')
    # ### end Alembic commands ###
