"""add file_content to documents

Revision ID: 2dc92537f2f0
Revises: c83d59c15fdd
Create Date: 2025-10-02 14:05:32.419250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dc92537f2f0'
down_revision: Union[str, None] = 'c83d59c15fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_content', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_content')
    # ### end Alembic commands ###
