"""add structured_data to documents

Revision ID: 5f4bd2c88679
Revises: 2dc92537f2f0
Create Date: 2025-10-03 11:48:47.540006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f4bd2c88679'
down_revision: Union[str, None] = '2dc92537f2f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('structured_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'structured_data')
    # ### end Alembic commands ###
