"""add status to documents

Revision ID: c83d59c15fdd
Revises: 22b8292475aa
Create Date: 2025-10-02 13:03:27.380521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83d59c15fdd'
down_revision: Union[str, None] = '22b8292475aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status', sa.String(), nullable=False, server_default='COMPLETED'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    # ### end Alembic commands ###
