# .github/workflows/deploy-backend.yml

name: Deploy Backend to Cloud Run

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**' # Only run if changes are in the backend folder
      - 'Dockerfile'   # Or if the Dockerfile itself changes

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GAR_LOCATION: us-west1 # Specify your Artifact Registry location
  SERVICE_NAME: ai-research-assistant-backend # The name of your Cloud Run service
  REGION: us-west1 # Specify your Cloud Run service region

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/backend:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/backend:latest
          flags: '--allow-unauthenticated' # Add this flag to keep the service public